### ISSUE TITLE
about clip-vit-large-patch14

### ISSUE THREAD

**Issue by silence-tang** [VamosC/CapHuman#6]
Hi, it seems that we should also download all the files related to clip-vit-large-patch14 and place these files under `/ckpts/clip-vit-large-patch14`, but the preparation instruction doesn't mention it. Could you please revise the preparation instruction?

**Comment by VamosC** [comment]
@silence-tang Thanks for pointing it out. We will update the instructions soon.

**Comment by VamosC** [comment]
If you specify openai/clip-vit-large-patch14 in the config file. clip-vit-large-patch14 will be downloaded automatically. https://github.com/VamosC/CapHuman/blob/4c735f7180527057a7acc375261a810b43337a06/models/cldm_v15.yaml#L26-L29

https://github.com/VamosC/CapHuman/blob/4c735f7180527057a7acc375261a810b43337a06/models/cldm_v15.yaml#L89-L92

Otherwise, you can download the files from https://huggingface.co/openai/clip-vit-large-patch14/tree/main and put it in the `ckpts/clip-vit-large-patch14`. Note that you should also modify the `version` in the config file.

You can find more details in the code.

https://github.com/VamosC/CapHuman/blob/4c735f7180527057a7acc375261a810b43337a06/ldm/modules/encoders/modules.py#L88-L100

https://github.com/VamosC/CapHuman/blob/4c735f7180527057a7acc375261a810b43337a06/ldm/modules/encoders/modules.py#L137-L149
